# Generated by Django 3.2.15 on 2022-09-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210409_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='awsurl',
            field=models.CharField(default='add', max_length=200, verbose_name='Player url'),
        ),
    ]
